exports.seed = function (knex, Promise) {
  return knex('types').del()
    .then(function () {
      return Promise.all([
        knex('types').insert({movie_id: 1, genre_id: 4}),
        knex('types').insert({movie_id: 1, genre_id: 5}),
        knex('types').insert({movie_id: 2, genre_id: 4}),
        knex('types').insert({movie_id: 2, genre_id: 5}),
        knex('types').insert({movie_id: 3, genre_id: 4}),
        knex('types').insert({movie_id: 3, genre_id: 5}),
        knex('types').insert({movie_id: 4, genre_id: 1}),
        knex('types').insert({movie_id: 4, genre_id: 4}),
        knex('types').insert({movie_id: 4, genre_id: 5}),
        knex('types').insert({movie_id: 5, genre_id: 4}),
        knex('types').insert({movie_id: 5, genre_id: 5}),
        knex('types').insert({movie_id: 6, genre_id: 11}),
        knex('types').insert({movie_id: 6, genre_id: 12}),
        knex('types').insert({movie_id: 6, genre_id: 5}),
        knex('types').insert({movie_id: 7, genre_id: 4}),
        knex('types').insert({movie_id: 7, genre_id: 5}),
        knex('types').insert({movie_id: 8, genre_id: 2}),
        knex('types').insert({movie_id: 8, genre_id: 5}),
        knex('types').insert({movie_id: 8, genre_id: 6}),
        knex('types').insert({movie_id: 9, genre_id: 10}),
        knex('types').insert({movie_id: 10, genre_id: 5}),
        knex('types').insert({movie_id: 11, genre_id: 2}),
        knex('types').insert({movie_id: 11, genre_id: 5}),
        knex('types').insert({movie_id: 11, genre_id: 6}),
        knex('types').insert({movie_id: 12, genre_id: 1}),
        knex('types').insert({movie_id: 12, genre_id: 2}),
        knex('types').insert({movie_id: 12, genre_id: 6}),
        knex('types').insert({movie_id: 13, genre_id: 3}),
        knex('types').insert({movie_id: 13, genre_id: 5}),
        knex('types').insert({movie_id: 13, genre_id: 13}),
        knex('types').insert({movie_id: 14, genre_id: 1}),
        knex('types').insert({movie_id: 14, genre_id: 2}),
        knex('types').insert({movie_id: 14, genre_id: 8}),
        knex('types').insert({movie_id: 15, genre_id: 2}),
        knex('types').insert({movie_id: 15, genre_id: 5}),
        knex('types').insert({movie_id: 15, genre_id: 6}),
        knex('types').insert({movie_id: 16, genre_id: 5}),
        knex('types').insert({movie_id: 17, genre_id: 4}),
        knex('types').insert({movie_id: 17, genre_id: 5}),
        knex('types').insert({movie_id: 18, genre_id: 1}),
        knex('types').insert({movie_id: 18, genre_id: 8}),
        knex('types').insert({movie_id: 19, genre_id: 2}),
        knex('types').insert({movie_id: 19, genre_id: 5}),
        knex('types').insert({movie_id: 20, genre_id: 1}),
        knex('types').insert({movie_id: 20, genre_id: 2}),
        knex('types').insert({movie_id: 20, genre_id: 6})
      ]);
    });
};
